### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [SuperBruceJia/EEG-DL#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.1b0. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary eeg-dl -w /tmp/ext eeg-dl==1.1b0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting eeg-dl==1.1b0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/e27/50c838567b641/eeg-dl-1.1b0.tar.gz (6.0 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-415swdkb/eeg-dl/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-415swdkb/eeg-dl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-415swdkb/eeg-dl/pip-egg-info
         cwd: /tmp/pip-wheel-415swdkb/eeg-dl/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-415swdkb/eeg-dl/setup.py", line 13, in <module>
        with open(path.join(here, 'DL_Models', '__init__.py'), encoding='utf-8') as f:
      File "/usr/lib/python3.8/codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-415swdkb/eeg-dl/DL_Models/__init__.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by SuperBruceJia** [comment]
Bro,  I suggest you download the GitHub files and use the models directly.

**Comment by SuperBruceJia** [comment]
Please follow the -> Usage Demo <- here: https://github.com/SuperBruceJia/EEG-DL.
